-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8bPuELfs7YQNod5R
TGlddKy1kGaq8OrDRxbpmt6uSCugCgYIKoZIzj0DAQehRANCAAQR/Zd9vu7DIA2z
vy+ojPv7dq6EPV1DBi2IWtsnCmoN8jlkhYn9LD0pgbEMNAUzUMveDiaf5G3SY/ou
viaYB99S
-----END PRIVATE KEY-----